apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lw2k6mpx7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lw2k6mpx7-nodejs 
  name: lw2k6mpx7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lw2k6mpx7-nodejs 
